# Generated by Django 4.1 on 2023-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('location', models.TextField()),
                ('region', models.CharField(choices=[('Accra', 'Accra'), ('Ashanti', 'Ashanti'), ('Eastern', 'Eastern'), ('Central', 'Central'), ('Volta', 'Volta'), ('Northern', 'Northern'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Western', 'Western'), ('Brong Ahafo', 'Brong Ahafo')], max_length=200)),
            ],
        ),
    ]
